# Generated by Django 5.2 on 2025-04-25 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keystrokefeature',
            name='feature_vector',
            field=models.JSONField(),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('time_since_last_txn', models.FloatField()),
                ('hour_of_day', models.IntegerField()),
                ('distance_from_home', models.FloatField()),
                ('merchant_risk', models.IntegerField()),
                ('merchant_category', models.CharField(max_length=50)),
                ('is_fraud', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('anomaly_score', models.FloatField(blank=True, null=True)),
                ('predicted_fraud', models.BooleanField(blank=True, null=True)),
                ('txn_frequency', models.IntegerField(blank=True, null=True)),
                ('amount_deviation', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
